### ISSUE TITLE
Setting TargetJDK is lost when not tabbing out of that table cell

### ISSUE THREAD

**Issue by jborgers** [amitdev/PMD-Intellij#45]
In File - Settings - PMD - Options - TagetJDK, you need to set your Java version. Default is 1.4 now, and if you leave it like that, for example Enum classes or @Annotations will result in Parse errors.

If you change it to e.g. 1.8 and OK or Apply, the value does not really change. If you revisit the options, you see it is still on 1.4. If you tab out of the cell first, it behaves correctly: the value will persist.

I would like the changed value to persist without the need to tab out of the cell.

See #36

**Comment by jborgers** [comment]
Hi Amit,

Good to see the merge!

When you think the new version will available for download in IntelliJ?

Kind regards, met vriendelijke groet,

Jeroen Borgers

drs. Jeroen Borgers
Principal Consultant
jPinpoint Performance Services, www jpinpoint com, The Netherlands.
Mobile: +31(0)6-30128951, e-mail: jborgers at jpinpoint com

2018-02-07 10:10 GMT+01:00 Amit Dev <notifications@github.com>:

**Comment by amitdev** [comment]
I merged it, so you should be able to download now.

Regards,
Amit

**Comment by jborgers** [comment]
Hi Amit,

When I search pmd in my Plugins list in IntelliJ, I still see version
1.8.3.
Version 1.8.4 with these changes should be available already?

Kind regards, met vriendelijke groet,

Jeroen Borgers

drs. Jeroen Borgers
Principal Consultant
jPinpoint Performance Services, www jpinpoint com, The Netherlands.
Mobile: +31(0)6-30128951, e-mail: jborgers at jpinpoint com

2018-02-07 11:39 GMT+01:00 Amit Dev <notifications@github.com>:
